*********************************************************************************************************
*																										*
*			Equilibrium in the Market for Public School Teachers	(Biasi, Fu, Stromme JPE)			*
*			Master file for producing resulting exhibits												*
*			June 2026																					*
*********************************************************************************************************

clear all
macro drop _all
set maxvar 32000
set seed 12345
set sortseed 12345
set scheme plotplain
set varabbrev on

********************************************************************************
* Locate the replication root
********************************************************************************
* Canonical invocation: start Stata in the replication root and run
*     do code/produce_exhibits.do
* Running from code/ is also supported.
local launch_dir `"`c(pwd)'"'
capture confirm file `"`launch_dir'/code/produce_exhibits.do"'
if _rc {
    capture confirm file `"`launch_dir'/produce_exhibits.do"'
    if !_rc {
        quietly cd `"`launch_dir'/.."'
        local launch_dir `"`c(pwd)'"'
    }
}
capture confirm file `"`launch_dir'/code/produce_exhibits.do"'
if _rc {
    display as error "Could not locate the replication root."
    display as error "Start Stata in the replication root and run: do code/produce_exhibits.do"
    exit 601
}
global rootpath `"`launch_dir'"'
quietly cd "$rootpath"

global code = "$rootpath/code/"
global fortran_code = "$code/fortran_model/"
global est = "$rootpath/model_data/"
global out = "$rootpath/out_synth/"


********************************************************************************
* Generating Exhibits That Rely on Generated model_data & simulation_data
*    (these are produced by master.do, no fortran needed)
********************************************************************************

* Figure 4
do $code/descriptives/Figure_4.do

* Figure B9 
*  Note: source data for this is generated by the R code in Figure_B9 folder
do $code/Figure_B9/Figure_B9.do

********************************************************************************
* Generating Exhibits From Model Results
*    (must have results from fortran code already produced for this code to run)
********************************************************************************

* Table 5 & Table A1 (model estimate summary, w/ std errs)
do $code/descriptives/Table_5_Table_A1.do 

* Table 6 (flexible vs rigid pay)
do $code/descriptives/Table_6.do 

* Table 7 (State-Funded Bonuses)
do $code/descriptives/Table_7.do 

* Table 8 (Moving Costs, Resistance Costs, and Policy Impacts)
do $code/descriptives/Table_8.do 

* Table A2 (Model Fit: OLS of Teacher-District Match)
do $code/descriptives/Table_A2.do

* Table A3 (Model Fit: District Wage Schedules)
do $code/descriptives/Table_A3_PanelA.do 
do $code/descriptives/Table_A3_PanelB.do 

* Table B14 (Parameter Perturbation Exercise)
do $code/descriptives/Table_B14.do 

* Table B15 (Allocating Teachers at Will)
do $code/descriptives/Table_B15.do

* Table B16 (Extensive Margin)
do $code/descriptives/Table_B16.do 

* Table B17 (Extensive Margin & Repeated Game)
do $code/descriptives/Table_B17.do 

* Table B18 (State-Funded Bonuses)
do $code/descriptives/Table_B18.do

* Table B19 (Higher Bonus Rates)
do $code/descriptives/Table_B19.do

* Table B20 (Zero Wage Setting Cost)
do $code/descriptives/Table_B20.do 

* Table B22 (Model Fit: Avg District Employee Characteristics)
do $code/descriptives/Table_B22.do 

* Table B23 (Model Fit: OLS of District Wage Schedule)
do $code/descriptives/Table_B23.do 

* Table B24 (Pre-Act 10 Model Validation: OLS of Teacher-District Match)
do $code/descriptives/Table_B24.do 

* Table B25 (Pre-Act 10 Model Validation: Avg District Employee Characteristics)
do $code/descriptives/Table_B25.do 

